apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firearms-search

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml

nameSuffix: -prod

replicas:
  - name: firearms-search
    count: 3

images:
  - name: firearms-search
    newTag: latest

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: firearms-search

configMapGenerator:
  - name: firearms-search-config
    behavior: replace
    literals:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
