apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firearms-search

bases:
  - ../../base

nameSuffix: -prod

replicas:
  - name: firearms-search
    count: 3

images:
  - name: firearms-search
    newTag: latest

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress.yaml

configMapGenerator:
  - name: firearms-search-config
    behavior: merge
    literals:
      - NODE_ENV=production
