apiVersion: v1
kind: Service
metadata:
  name: firearms-search
  namespace: firearms-search
spec:
  type: ClusterIP
  selector:
    app: firearms-search
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
