apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firearms-search

bases:
  - ../../base

nameSuffix: -dev

replicas:
  - name: firearms-search
    count: 1

images:
  - name: firearms-search
    newTag: develop

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: firearms-search-config
    behavior: merge
    literals:
      - NODE_ENV=development
