apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: firearms-search

resources:
  - ../../base

nameSuffix: -dev

replicas:
  - name: firearms-search
    count: 1

images:
  - name: firearms-search
    newTag: develop

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: firearms-search

configMapGenerator:
  - name: firearms-search-config
    behavior: replace
    literals:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
